// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 15.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace TestoviCodedUI
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public partial class UIMap
    {
        
        /// <summary>
        /// dodavanjePosiljke - Use 'dodavanjePosiljkeParams' to pass parameters into this method.
        /// </summary>
        public void dodavanjePosiljke()
        {
            #region Variable Declarations
            WinEdit uITextBox5Edit = this.UIForm1Window.UITextBox5Window.UITextBox5Edit;
            WinEdit uITextBox6Edit = this.UIForm1Window.UITextBox6Window.UITextBox6Edit;
            WinEdit uITextBox7Edit = this.UIForm1Window.UITextBox7Window.UITextBox7Edit;
            WinWindow uITextBox8Window = this.UIForm1Window.UILicnipodaciGroup.UITextBox8Window;
            WinEdit uITextBox8Edit = this.UIForm1Window.UITextBox8Window.UITextBox8Edit;
            WinEdit uITextBox9Edit = this.UIForm1Window.UITextBox9Window.UITextBox9Edit;
            WinEdit uITextBox2Edit = this.UIForm1Window.UITextBox2Window.UITextBox2Edit;
            WinEdit uITextBox3Edit = this.UIForm1Window.UITextBox3Window.UITextBox3Edit;
            WinEdit uITextBox4Edit = this.UIForm1Window.UITextBox4Window.UITextBox4Edit;
            WinSlider uITakseSlider = this.UIForm1Window.UITrackBar1Window.UITakseSlider;
            WinButton uIRegistrujpošiljkuButton = this.UIForm1Window.UIRegistrujpošiljkuWindow.UIRegistrujpošiljkuButton;
            #endregion

            // Type 'Haris' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjePosiljkeParams.UITextBox5EditText;

            // Type 'Masovic' in 'textBox6' text box
            uITextBox6Edit.Text = this.dodavanjePosiljkeParams.UITextBox6EditText;

            // Type '29221196170003' in 'textBox7' text box
            uITextBox7Edit.Text = this.dodavanjePosiljkeParams.UITextBox7EditText;

            // Click 'textBox8' window
            Mouse.Click(uITextBox8Window, new Point(29, 18));

            // Type '033/225-884' in 'textBox8' text box
            uITextBox8Edit.Text = this.dodavanjePosiljkeParams.UITextBox8EditText;

            // Type 'hehe' in 'textBox9' text box
            uITextBox9Edit.Text = this.dodavanjePosiljkeParams.UITextBox9EditText;

            // Type '150' in 'textBox2' text box
            uITextBox2Edit.Text = this.dodavanjePosiljkeParams.UITextBox2EditText;

            // Type '1.2' in 'textBox3' text box
            uITextBox3Edit.Text = this.dodavanjePosiljkeParams.UITextBox3EditText;

            // Type '0.25' in 'textBox4' text box
            uITextBox4Edit.Text = this.dodavanjePosiljkeParams.UITextBox4EditText;

            // Set position '5' in 'Takse:' slider
            uITakseSlider.PositionAsString = this.dodavanjePosiljkeParams.UITakseSliderPositionAsString;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(139, 38));

            // Type 'Haris Novi' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjePosiljkeParams.UITextBox5EditText1;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(183, 36));
        }
        
        /// <summary>
        /// dodavanjeNovePosiljke - Use 'dodavanjeNovePosiljkeParams' to pass parameters into this method.
        /// </summary>
        public void dodavanjeNovePosiljke()
        {
            #region Variable Declarations
            WinEdit uITextBox5Edit = this.UIForm1Window.UITextBox5Window.UITextBox5Edit;
            WinEdit uITextBox6Edit = this.UIForm1Window.UITextBox6Window.UITextBox6Edit;
            WinEdit uITextBox7Edit = this.UIForm1Window.UITextBox7Window.UITextBox7Edit;
            WinWindow uITextBox8Window = this.UIForm1Window.UILicnipodaciGroup.UITextBox8Window;
            WinEdit uITextBox8Edit = this.UIForm1Window.UITextBox8Window.UITextBox8Edit;
            WinEdit uITextBox9Edit = this.UIForm1Window.UITextBox9Window.UITextBox9Edit;
            WinEdit uITextBox2Edit = this.UIForm1Window.UITextBox2Window.UITextBox2Edit;
            WinEdit uITextBox3Edit = this.UIForm1Window.UITextBox3Window.UITextBox3Edit;
            WinEdit uITextBox4Edit = this.UIForm1Window.UITextBox4Window.UITextBox4Edit;
            WinSlider uITakseSlider = this.UIForm1Window.UITrackBar1Window.UITakseSlider;
            WinButton uIRegistrujpošiljkuButton = this.UIForm1Window.UIRegistrujpošiljkuWindow.UIRegistrujpošiljkuButton;
            #endregion

            // Type 'Haris' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox5EditText;

            // Type 'Masovic' in 'textBox6' text box
            uITextBox6Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox6EditText;

            // Type '29221196170003' in 'textBox7' text box
            uITextBox7Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox7EditText;

            // Click 'textBox8' window
            Mouse.Click(uITextBox8Window, new Point(29, 18));

            // Type '033/225-884' in 'textBox8' text box
            uITextBox8Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox8EditText;

            // Type 'hehe' in 'textBox9' text box
            uITextBox9Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox9EditText;

            // Type '150' in 'textBox2' text box
            uITextBox2Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox2EditText;

            // Type '1.2' in 'textBox3' text box
            uITextBox3Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox3EditText;

            // Type '0.25' in 'textBox4' text box
            uITextBox4Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox4EditText;

            // Set position '5' in 'Takse:' slider
            uITakseSlider.PositionAsString = this.dodavanjeNovePosiljkeParams.UITakseSliderPositionAsString;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(139, 38));

            // Type 'Haris Novi' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox5EditText1;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(183, 36));

            // Type 'Haris' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox5EditText2;

            // Type '{Tab}' in 'textBox5' text box
            Keyboard.SendKeys(uITextBox5Edit, this.dodavanjeNovePosiljkeParams.UITextBox5EditSendKeys, ModifierKeys.None);

            // Type 'Masovic' in 'textBox6' text box
            uITextBox6Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox6EditText1;

            // Type '2822993170003' in 'textBox7' text box
            uITextBox7Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox7EditText1;

            // Type '033/225-883' in 'textBox8' text box
            uITextBox8Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox8EditText1;

            // Type 'bez' in 'textBox9' text box
            uITextBox9Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox9EditText1;

            // Type '250' in 'textBox2' text box
            uITextBox2Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox2EditText1;

            // Type '1.25' in 'textBox3' text box
            uITextBox3Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox3EditText1;

            // Type '15' in 'textBox4' text box
            uITextBox4Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox4EditText1;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(107, 25));

            // Type 'Haris Novi' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjeNovePosiljkeParams.UITextBox5EditText3;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(161, 22));
        }
        
        /// <summary>
        /// dodavanjePosiljkeNove - Use 'dodavanjePosiljkeNoveParams' to pass parameters into this method.
        /// </summary>
        public void dodavanjePosiljkeNove()
        {
            #region Variable Declarations
            WinWindow uITextBox5Window = this.UIForm1Window.UILicnipodaciGroup.UITextBox5Window;
            WinEdit uITextBox5Edit = this.UIForm1Window.UITextBox5Window.UITextBox5Edit;
            WinEdit uITextBox6Edit = this.UIForm1Window.UITextBox6Window.UITextBox6Edit;
            WinEdit uITextBox7Edit = this.UIForm1Window.UITextBox7Window.UITextBox7Edit;
            WinEdit uITextBox8Edit = this.UIForm1Window.UITextBox8Window.UITextBox8Edit;
            WinEdit uITextBox9Edit = this.UIForm1Window.UITextBox9Window.UITextBox9Edit;
            WinEdit uITextBox2Edit = this.UIForm1Window.UITextBox2Window.UITextBox2Edit;
            WinEdit uITextBox3Edit = this.UIForm1Window.UITextBox3Window.UITextBox3Edit;
            WinSlider uITakseSlider = this.UIForm1Window.UITrackBar1Window.UITakseSlider;
            WinButton uIRegistrujpošiljkuButton = this.UIForm1Window.UIRegistrujpošiljkuWindow.UIRegistrujpošiljkuButton;
            #endregion

            // Click 'textBox5' window
            Mouse.Click(uITextBox5Window, new Point(29, 18));

            // Type 'Haris' in 'textBox5' text box
            uITextBox5Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox5EditText;

            // Type '{Tab}' in 'textBox5' text box
            Keyboard.SendKeys(uITextBox5Edit, this.dodavanjePosiljkeNoveParams.UITextBox5EditSendKeys, ModifierKeys.None);

            // Type 'Masovic' in 'textBox6' text box
            uITextBox6Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox6EditText;

            // Type '2811995160004' in 'textBox7' text box
            uITextBox7Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox7EditText;

            // Type '033/225-883' in 'textBox8' text box
            uITextBox8Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox8EditText;

            // Type 'bez' in 'textBox9' text box
            uITextBox9Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox9EditText;

            // Type '250' in 'textBox2' text box
            uITextBox2Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox2EditText;

            // Type '1.25' in 'textBox3' text box
            uITextBox3Edit.Text = this.dodavanjePosiljkeNoveParams.UITextBox3EditText;

            // Set position '4' in 'Takse:' slider
            uITakseSlider.PositionAsString = this.dodavanjePosiljkeNoveParams.UITakseSliderPositionAsString;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(107, 25));
        }
        
        /// <summary>
        /// brisanjeKreiranog - Use 'brisanjeKreiranogParams' to pass parameters into this method.
        /// </summary>
        public void brisanjeKreiranog()
        {
            #region Variable Declarations
            WinEdit uITextBox5Edit = this.UIForm1Window.UITextBox5Window.UITextBox5Edit;
            WinEdit uITextBox6Edit = this.UIForm1Window.UITextBox6Window.UITextBox6Edit;
            WinEdit uITextBox7Edit = this.UIForm1Window.UITextBox7Window.UITextBox7Edit;
            WinEdit uITextBox8Edit = this.UIForm1Window.UITextBox8Window.UITextBox8Edit;
            WinEdit uITextBox9Edit = this.UIForm1Window.UITextBox9Window.UITextBox9Edit;
            WinEdit uITextBox2Edit = this.UIForm1Window.UITextBox2Window.UITextBox2Edit;
            WinEdit uITextBox3Edit = this.UIForm1Window.UITextBox3Window.UITextBox3Edit;
            WinEdit uITextBox4Edit = this.UIForm1Window.UITextBox4Window.UITextBox4Edit;
            WinButton uIRegistrujpošiljkuButton = this.UIForm1Window.UIRegistrujpošiljkuWindow.UIRegistrujpošiljkuButton;
            WinRowHeader uIItemRowHeader = this.UIForm1Window.UIDataGridView1Window.UIDataGridViewTable.UIRow0Row1.UIItemRowHeader;
            #endregion

            // Type 'Kreirani' in 'textBox5' text box
            uITextBox5Edit.Text = this.brisanjeKreiranogParams.UITextBox5EditText;

            // Type 'Novi' in 'textBox6' text box
            uITextBox6Edit.Text = this.brisanjeKreiranogParams.UITextBox6EditText;

            // Type '2911933120003' in 'textBox7' text box
            uITextBox7Edit.Text = this.brisanjeKreiranogParams.UITextBox7EditText;

            // Type '033/534-232' in 'textBox8' text box
            uITextBox8Edit.Text = this.brisanjeKreiranogParams.UITextBox8EditText;

            // Type 'he' in 'textBox9' text box
            uITextBox9Edit.Text = this.brisanjeKreiranogParams.UITextBox9EditText;

            // Type '1' in 'textBox2' text box
            uITextBox2Edit.Text = this.brisanjeKreiranogParams.UITextBox2EditText;

            // Type '1' in 'textBox3' text box
            uITextBox3Edit.Text = this.brisanjeKreiranogParams.UITextBox3EditText;

            // Type '1' in 'textBox4' text box
            uITextBox4Edit.Text = this.brisanjeKreiranogParams.UITextBox4EditText;

            // Click 'Registruj pošiljku' button
            Mouse.Click(uIRegistrujpošiljkuButton, new Point(89, 17));

            // Click row header
            Mouse.Click(uIItemRowHeader, new Point(24, 13));
        }
        
        /// <summary>
        /// izPostavke - Use 'izPostavkeParams' to pass parameters into this method.
        /// </summary>
        public void izPostavke()
        {
            #region Variable Declarations
            WinEdit uITextBox2Edit = this.UIForm1Window.UITextBox2Window.UITextBox2Edit;
            WinEdit uITextBox3Edit = this.UIForm1Window.UITextBox3Window.UITextBox3Edit;
            WinEdit uITextBox4Edit = this.UIForm1Window.UITextBox4Window.UITextBox4Edit;
            WinSlider uITakseSlider = this.UIForm1Window.UITrackBar1Window.UITakseSlider;
            WinButton uIIzracunajcijenuisporButton = this.UIForm1Window.UIIzracunajcijenuisporWindow.UIIzracunajcijenuisporButton;
            #endregion

            // Type '9274,000' in 'textBox2' text box
            uITextBox2Edit.Text = this.izPostavkeParams.UITextBox2EditText;

            // Type '1,567' in 'textBox3' text box
            uITextBox3Edit.Text = this.izPostavkeParams.UITextBox3EditText;

            // Type '0,125' in 'textBox4' text box
            uITextBox4Edit.Text = this.izPostavkeParams.UITextBox4EditText;

            // Set position '5' in 'Takse:' slider
            uITakseSlider.PositionAsString = this.izPostavkeParams.UITakseSliderPositionAsString;

            // Click 'Izracunaj cijenu isporuke' button
            Mouse.Click(uIIzracunajcijenuisporButton, new Point(235, 16));
        }
        
        #region Properties
        public virtual dodavanjePosiljkeParams dodavanjePosiljkeParams
        {
            get
            {
                if ((this.mdodavanjePosiljkeParams == null))
                {
                    this.mdodavanjePosiljkeParams = new dodavanjePosiljkeParams();
                }
                return this.mdodavanjePosiljkeParams;
            }
        }
        
        public virtual dodavanjeNovePosiljkeParams dodavanjeNovePosiljkeParams
        {
            get
            {
                if ((this.mdodavanjeNovePosiljkeParams == null))
                {
                    this.mdodavanjeNovePosiljkeParams = new dodavanjeNovePosiljkeParams();
                }
                return this.mdodavanjeNovePosiljkeParams;
            }
        }
        
        public virtual dodavanjePosiljkeNoveParams dodavanjePosiljkeNoveParams
        {
            get
            {
                if ((this.mdodavanjePosiljkeNoveParams == null))
                {
                    this.mdodavanjePosiljkeNoveParams = new dodavanjePosiljkeNoveParams();
                }
                return this.mdodavanjePosiljkeNoveParams;
            }
        }
        
        public virtual brisanjeKreiranogParams brisanjeKreiranogParams
        {
            get
            {
                if ((this.mbrisanjeKreiranogParams == null))
                {
                    this.mbrisanjeKreiranogParams = new brisanjeKreiranogParams();
                }
                return this.mbrisanjeKreiranogParams;
            }
        }
        
        public virtual izPostavkeParams izPostavkeParams
        {
            get
            {
                if ((this.mizPostavkeParams == null))
                {
                    this.mizPostavkeParams = new izPostavkeParams();
                }
                return this.mizPostavkeParams;
            }
        }
        
        public UIForm1Window UIForm1Window
        {
            get
            {
                if ((this.mUIForm1Window == null))
                {
                    this.mUIForm1Window = new UIForm1Window();
                }
                return this.mUIForm1Window;
            }
        }
        
        public UIZadaca3Window UIZadaca3Window
        {
            get
            {
                if ((this.mUIZadaca3Window == null))
                {
                    this.mUIZadaca3Window = new UIZadaca3Window();
                }
                return this.mUIZadaca3Window;
            }
        }
        #endregion
        
        #region Fields
        private dodavanjePosiljkeParams mdodavanjePosiljkeParams;
        
        private dodavanjeNovePosiljkeParams mdodavanjeNovePosiljkeParams;
        
        private dodavanjePosiljkeNoveParams mdodavanjePosiljkeNoveParams;
        
        private brisanjeKreiranogParams mbrisanjeKreiranogParams;
        
        private izPostavkeParams mizPostavkeParams;
        
        private UIForm1Window mUIForm1Window;
        
        private UIZadaca3Window mUIZadaca3Window;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'dodavanjePosiljke'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class dodavanjePosiljkeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Haris' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText = "Haris";
        
        /// <summary>
        /// Type 'Masovic' in 'textBox6' text box
        /// </summary>
        public string UITextBox6EditText = "Masovic";
        
        /// <summary>
        /// Type '29221196170003' in 'textBox7' text box
        /// </summary>
        public string UITextBox7EditText = "29221196170003";
        
        /// <summary>
        /// Type '033/225-884' in 'textBox8' text box
        /// </summary>
        public string UITextBox8EditText = "033/225-884";
        
        /// <summary>
        /// Type 'hehe' in 'textBox9' text box
        /// </summary>
        public string UITextBox9EditText = "hehe";
        
        /// <summary>
        /// Type '150' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "150";
        
        /// <summary>
        /// Type '1.2' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "1.2";
        
        /// <summary>
        /// Type '0.25' in 'textBox4' text box
        /// </summary>
        public string UITextBox4EditText = "0.25";
        
        /// <summary>
        /// Set position '5' in 'Takse:' slider
        /// </summary>
        public string UITakseSliderPositionAsString = "5";
        
        /// <summary>
        /// Type 'Haris Novi' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText1 = "Haris Novi";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'dodavanjeNovePosiljke'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class dodavanjeNovePosiljkeParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Haris' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText = "Haris";
        
        /// <summary>
        /// Type 'Masovic' in 'textBox6' text box
        /// </summary>
        public string UITextBox6EditText = "Masovic";
        
        /// <summary>
        /// Type '29221196170003' in 'textBox7' text box
        /// </summary>
        public string UITextBox7EditText = "29221196170003";
        
        /// <summary>
        /// Type '033/225-884' in 'textBox8' text box
        /// </summary>
        public string UITextBox8EditText = "033/225-884";
        
        /// <summary>
        /// Type 'hehe' in 'textBox9' text box
        /// </summary>
        public string UITextBox9EditText = "hehe";
        
        /// <summary>
        /// Type '150' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "150";
        
        /// <summary>
        /// Type '1.2' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "1.2";
        
        /// <summary>
        /// Type '0.25' in 'textBox4' text box
        /// </summary>
        public string UITextBox4EditText = "0.25";
        
        /// <summary>
        /// Set position '5' in 'Takse:' slider
        /// </summary>
        public string UITakseSliderPositionAsString = "5";
        
        /// <summary>
        /// Type 'Haris Novi' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText1 = "Haris Novi";
        
        /// <summary>
        /// Type 'Haris' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText2 = "Haris";
        
        /// <summary>
        /// Type '{Tab}' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Masovic' in 'textBox6' text box
        /// </summary>
        public string UITextBox6EditText1 = "Masovic";
        
        /// <summary>
        /// Type '2822993170003' in 'textBox7' text box
        /// </summary>
        public string UITextBox7EditText1 = "2822993170003";
        
        /// <summary>
        /// Type '033/225-883' in 'textBox8' text box
        /// </summary>
        public string UITextBox8EditText1 = "033/225-883";
        
        /// <summary>
        /// Type 'bez' in 'textBox9' text box
        /// </summary>
        public string UITextBox9EditText1 = "bez";
        
        /// <summary>
        /// Type '250' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText1 = "250";
        
        /// <summary>
        /// Type '1.25' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText1 = "1.25";
        
        /// <summary>
        /// Type '15' in 'textBox4' text box
        /// </summary>
        public string UITextBox4EditText1 = "15";
        
        /// <summary>
        /// Type 'Haris Novi' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText3 = "Haris Novi";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'dodavanjePosiljkeNove'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class dodavanjePosiljkeNoveParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Haris' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText = "Haris";
        
        /// <summary>
        /// Type '{Tab}' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type 'Masovic' in 'textBox6' text box
        /// </summary>
        public string UITextBox6EditText = "Masovic";
        
        /// <summary>
        /// Type '2811995160004' in 'textBox7' text box
        /// </summary>
        public string UITextBox7EditText = "2811995160004";
        
        /// <summary>
        /// Type '033/225-883' in 'textBox8' text box
        /// </summary>
        public string UITextBox8EditText = "033/225-883";
        
        /// <summary>
        /// Type 'bez' in 'textBox9' text box
        /// </summary>
        public string UITextBox9EditText = "bez";
        
        /// <summary>
        /// Type '250' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "250";
        
        /// <summary>
        /// Type '1.25' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "1.25";
        
        /// <summary>
        /// Set position '4' in 'Takse:' slider
        /// </summary>
        public string UITakseSliderPositionAsString = "4";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'brisanjeKreiranog'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class brisanjeKreiranogParams
    {
        
        #region Fields
        /// <summary>
        /// Type 'Kreirani' in 'textBox5' text box
        /// </summary>
        public string UITextBox5EditText = "Kreirani";
        
        /// <summary>
        /// Type 'Novi' in 'textBox6' text box
        /// </summary>
        public string UITextBox6EditText = "Novi";
        
        /// <summary>
        /// Type '2911933120003' in 'textBox7' text box
        /// </summary>
        public string UITextBox7EditText = "2911933120003";
        
        /// <summary>
        /// Type '033/534-232' in 'textBox8' text box
        /// </summary>
        public string UITextBox8EditText = "033/534-232";
        
        /// <summary>
        /// Type 'he' in 'textBox9' text box
        /// </summary>
        public string UITextBox9EditText = "he";
        
        /// <summary>
        /// Type '1' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "1";
        
        /// <summary>
        /// Type '1' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "1";
        
        /// <summary>
        /// Type '1' in 'textBox4' text box
        /// </summary>
        public string UITextBox4EditText = "1";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'izPostavke'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class izPostavkeParams
    {
        
        #region Fields
        /// <summary>
        /// Type '9274,000' in 'textBox2' text box
        /// </summary>
        public string UITextBox2EditText = "9274,000";
        
        /// <summary>
        /// Type '1,567' in 'textBox3' text box
        /// </summary>
        public string UITextBox3EditText = "1,567";
        
        /// <summary>
        /// Type '0,125' in 'textBox4' text box
        /// </summary>
        public string UITextBox4EditText = "0,125";
        
        /// <summary>
        /// Set position '5' in 'Takse:' slider
        /// </summary>
        public string UITakseSliderPositionAsString = "5";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIForm1Window : WinWindow
    {
        
        public UIForm1Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Form1";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UITextBox5Window UITextBox5Window
        {
            get
            {
                if ((this.mUITextBox5Window == null))
                {
                    this.mUITextBox5Window = new UITextBox5Window(this);
                }
                return this.mUITextBox5Window;
            }
        }
        
        public UITextBox6Window UITextBox6Window
        {
            get
            {
                if ((this.mUITextBox6Window == null))
                {
                    this.mUITextBox6Window = new UITextBox6Window(this);
                }
                return this.mUITextBox6Window;
            }
        }
        
        public UITextBox7Window UITextBox7Window
        {
            get
            {
                if ((this.mUITextBox7Window == null))
                {
                    this.mUITextBox7Window = new UITextBox7Window(this);
                }
                return this.mUITextBox7Window;
            }
        }
        
        public UITextBox8Window UITextBox8Window
        {
            get
            {
                if ((this.mUITextBox8Window == null))
                {
                    this.mUITextBox8Window = new UITextBox8Window(this);
                }
                return this.mUITextBox8Window;
            }
        }
        
        public UILicnipodaciGroup UILicnipodaciGroup
        {
            get
            {
                if ((this.mUILicnipodaciGroup == null))
                {
                    this.mUILicnipodaciGroup = new UILicnipodaciGroup(this);
                }
                return this.mUILicnipodaciGroup;
            }
        }
        
        public UITextBox9Window UITextBox9Window
        {
            get
            {
                if ((this.mUITextBox9Window == null))
                {
                    this.mUITextBox9Window = new UITextBox9Window(this);
                }
                return this.mUITextBox9Window;
            }
        }
        
        public UITextBox2Window UITextBox2Window
        {
            get
            {
                if ((this.mUITextBox2Window == null))
                {
                    this.mUITextBox2Window = new UITextBox2Window(this);
                }
                return this.mUITextBox2Window;
            }
        }
        
        public UITextBox3Window UITextBox3Window
        {
            get
            {
                if ((this.mUITextBox3Window == null))
                {
                    this.mUITextBox3Window = new UITextBox3Window(this);
                }
                return this.mUITextBox3Window;
            }
        }
        
        public UITrackBar1Window UITrackBar1Window
        {
            get
            {
                if ((this.mUITrackBar1Window == null))
                {
                    this.mUITrackBar1Window = new UITrackBar1Window(this);
                }
                return this.mUITrackBar1Window;
            }
        }
        
        public UIRegistrujpošiljkuWindow UIRegistrujpošiljkuWindow
        {
            get
            {
                if ((this.mUIRegistrujpošiljkuWindow == null))
                {
                    this.mUIRegistrujpošiljkuWindow = new UIRegistrujpošiljkuWindow(this);
                }
                return this.mUIRegistrujpošiljkuWindow;
            }
        }
        
        public UIPodacioposiljciWindow UIPodacioposiljciWindow
        {
            get
            {
                if ((this.mUIPodacioposiljciWindow == null))
                {
                    this.mUIPodacioposiljciWindow = new UIPodacioposiljciWindow(this);
                }
                return this.mUIPodacioposiljciWindow;
            }
        }
        
        public UIPodacioposiljciGroup UIPodacioposiljciGroup
        {
            get
            {
                if ((this.mUIPodacioposiljciGroup == null))
                {
                    this.mUIPodacioposiljciGroup = new UIPodacioposiljciGroup(this);
                }
                return this.mUIPodacioposiljciGroup;
            }
        }
        
        public UITextBox4Window UITextBox4Window
        {
            get
            {
                if ((this.mUITextBox4Window == null))
                {
                    this.mUITextBox4Window = new UITextBox4Window(this);
                }
                return this.mUITextBox4Window;
            }
        }
        
        public UIDataGridView1Window UIDataGridView1Window
        {
            get
            {
                if ((this.mUIDataGridView1Window == null))
                {
                    this.mUIDataGridView1Window = new UIDataGridView1Window(this);
                }
                return this.mUIDataGridView1Window;
            }
        }
        
        public UILicnipodaciWindow UILicnipodaciWindow
        {
            get
            {
                if ((this.mUILicnipodaciWindow == null))
                {
                    this.mUILicnipodaciWindow = new UILicnipodaciWindow(this);
                }
                return this.mUILicnipodaciWindow;
            }
        }
        
        public UIForm1TitleBar UIForm1TitleBar
        {
            get
            {
                if ((this.mUIForm1TitleBar == null))
                {
                    this.mUIForm1TitleBar = new UIForm1TitleBar(this);
                }
                return this.mUIForm1TitleBar;
            }
        }
        
        public UIIzracunajcijenuisporWindow UIIzracunajcijenuisporWindow
        {
            get
            {
                if ((this.mUIIzracunajcijenuisporWindow == null))
                {
                    this.mUIIzracunajcijenuisporWindow = new UIIzracunajcijenuisporWindow(this);
                }
                return this.mUIIzracunajcijenuisporWindow;
            }
        }
        #endregion
        
        #region Fields
        private UITextBox5Window mUITextBox5Window;
        
        private UITextBox6Window mUITextBox6Window;
        
        private UITextBox7Window mUITextBox7Window;
        
        private UITextBox8Window mUITextBox8Window;
        
        private UILicnipodaciGroup mUILicnipodaciGroup;
        
        private UITextBox9Window mUITextBox9Window;
        
        private UITextBox2Window mUITextBox2Window;
        
        private UITextBox3Window mUITextBox3Window;
        
        private UITrackBar1Window mUITrackBar1Window;
        
        private UIRegistrujpošiljkuWindow mUIRegistrujpošiljkuWindow;
        
        private UIPodacioposiljciWindow mUIPodacioposiljciWindow;
        
        private UIPodacioposiljciGroup mUIPodacioposiljciGroup;
        
        private UITextBox4Window mUITextBox4Window;
        
        private UIDataGridView1Window mUIDataGridView1Window;
        
        private UILicnipodaciWindow mUILicnipodaciWindow;
        
        private UIForm1TitleBar mUIForm1TitleBar;
        
        private UIIzracunajcijenuisporWindow mUIIzracunajcijenuisporWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox5Window : WinWindow
    {
        
        public UITextBox5Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox5";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox5Edit
        {
            get
            {
                if ((this.mUITextBox5Edit == null))
                {
                    this.mUITextBox5Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox5Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox5Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox5Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox6Window : WinWindow
    {
        
        public UITextBox6Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox6";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox6Edit
        {
            get
            {
                if ((this.mUITextBox6Edit == null))
                {
                    this.mUITextBox6Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox6Edit.SearchProperties[WinEdit.PropertyNames.Name] = "Komentar:";
                    this.mUITextBox6Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox6Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox6Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox7Window : WinWindow
    {
        
        public UITextBox7Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox7";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox7Edit
        {
            get
            {
                if ((this.mUITextBox7Edit == null))
                {
                    this.mUITextBox7Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox7Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox7Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox7Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox8Window : WinWindow
    {
        
        public UITextBox8Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox8";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox8Edit
        {
            get
            {
                if ((this.mUITextBox8Edit == null))
                {
                    this.mUITextBox8Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox8Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox8Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox8Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILicnipodaciGroup : WinGroup
    {
        
        public UILicnipodaciGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Licni podaci";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinWindow UITextBox9Window
        {
            get
            {
                if ((this.mUITextBox9Window == null))
                {
                    this.mUITextBox9Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUITextBox9Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITextBox9Window.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox9Window;
            }
        }
        
        public WinWindow UITextBox7Window
        {
            get
            {
                if ((this.mUITextBox7Window == null))
                {
                    this.mUITextBox7Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUITextBox7Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITextBox7Window.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
                    this.mUITextBox7Window.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox7Window;
            }
        }
        
        public WinWindow UITextBox8Window
        {
            get
            {
                if ((this.mUITextBox8Window == null))
                {
                    this.mUITextBox8Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUITextBox8Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITextBox8Window.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
                    this.mUITextBox8Window.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox8Window;
            }
        }
        
        public WinWindow UITextBox5Window
        {
            get
            {
                if ((this.mUITextBox5Window == null))
                {
                    this.mUITextBox5Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUITextBox5Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITextBox5Window.SearchProperties[WinWindow.PropertyNames.Instance] = "5";
                    this.mUITextBox5Window.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox5Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITextBox9Window;
        
        private WinWindow mUITextBox7Window;
        
        private WinWindow mUITextBox8Window;
        
        private WinWindow mUITextBox5Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox9Window : WinWindow
    {
        
        public UITextBox9Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox9";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox9Edit
        {
            get
            {
                if ((this.mUITextBox9Edit == null))
                {
                    this.mUITextBox9Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox9Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox9Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox9Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox2Window : WinWindow
    {
        
        public UITextBox2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox2Edit
        {
            get
            {
                if ((this.mUITextBox2Edit == null))
                {
                    this.mUITextBox2Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox2Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox2Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox2Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox3Window : WinWindow
    {
        
        public UITextBox3Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox3";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox3Edit
        {
            get
            {
                if ((this.mUITextBox3Edit == null))
                {
                    this.mUITextBox3Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox3Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox3Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox3Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITrackBar1Window : WinWindow
    {
        
        public UITrackBar1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "trackBar1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinSlider UITakseSlider
        {
            get
            {
                if ((this.mUITakseSlider == null))
                {
                    this.mUITakseSlider = new WinSlider(this);
                    #region Search Criteria
                    this.mUITakseSlider.SearchProperties[WinSlider.PropertyNames.Name] = "Takse:";
                    this.mUITakseSlider.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITakseSlider;
            }
        }
        #endregion
        
        #region Fields
        private WinSlider mUITakseSlider;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRegistrujpošiljkuWindow : WinWindow
    {
        
        public UIRegistrujpošiljkuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIRegistrujpošiljkuButton
        {
            get
            {
                if ((this.mUIRegistrujpošiljkuButton == null))
                {
                    this.mUIRegistrujpošiljkuButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIRegistrujpošiljkuButton.SearchProperties[WinButton.PropertyNames.Name] = "Registruj pošiljku";
                    this.mUIRegistrujpošiljkuButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIRegistrujpošiljkuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIRegistrujpošiljkuButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPodacioposiljciWindow : WinWindow
    {
        
        public UIPodacioposiljciWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinGroup UIPodacioposiljciGroup
        {
            get
            {
                if ((this.mUIPodacioposiljciGroup == null))
                {
                    this.mUIPodacioposiljciGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUIPodacioposiljciGroup.SearchProperties[WinControl.PropertyNames.Name] = "Podaci o posiljci";
                    this.mUIPodacioposiljciGroup.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIPodacioposiljciGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUIPodacioposiljciGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIPodacioposiljciGroup : WinGroup
    {
        
        public UIPodacioposiljciGroup(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "Podaci o posiljci";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinWindow UITextBox4Window
        {
            get
            {
                if ((this.mUITextBox4Window == null))
                {
                    this.mUITextBox4Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUITextBox4Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITextBox4Window.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox4Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUITextBox4Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UITextBox4Window : WinWindow
    {
        
        public UITextBox4Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "textBox4";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinEdit UITextBox4Edit
        {
            get
            {
                if ((this.mUITextBox4Edit == null))
                {
                    this.mUITextBox4Edit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITextBox4Edit.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUITextBox4Edit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITextBox4Edit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDataGridView1Window : WinWindow
    {
        
        public UIDataGridView1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "dataGridView1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIDataGridViewTable UIDataGridViewTable
        {
            get
            {
                if ((this.mUIDataGridViewTable == null))
                {
                    this.mUIDataGridViewTable = new UIDataGridViewTable(this);
                }
                return this.mUIDataGridViewTable;
            }
        }
        #endregion
        
        #region Fields
        private UIDataGridViewTable mUIDataGridViewTable;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIDataGridViewTable : WinTable
    {
        
        public UIDataGridViewTable(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinTable.PropertyNames.Name] = "DataGridView";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public UIRow0Row UIRow0Row
        {
            get
            {
                if ((this.mUIRow0Row == null))
                {
                    this.mUIRow0Row = new UIRow0Row(this);
                }
                return this.mUIRow0Row;
            }
        }
        
        public UIRow0Row1 UIRow0Row1
        {
            get
            {
                if ((this.mUIRow0Row1 == null))
                {
                    this.mUIRow0Row1 = new UIRow0Row1(this);
                }
                return this.mUIRow0Row1;
            }
        }
        #endregion
        
        #region Fields
        private UIRow0Row mUIRow0Row;
        
        private UIRow0Row1 mUIRow0Row1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow0Row : WinRow
    {
        
        public UIRow0Row(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinRow.PropertyNames.Value] = "50000;1.2;0.25;5;Haris Masovic;28229941400003;033/225-883;ne daj se amire, uz teb" +
                "e sam";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinCell UIItem50000Cell
        {
            get
            {
                if ((this.mUIItem50000Cell == null))
                {
                    this.mUIItem50000Cell = new WinCell(this);
                    #region Search Criteria
                    this.mUIItem50000Cell.SearchProperties[WinCell.PropertyNames.Value] = "50000";
                    this.mUIItem50000Cell.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItem50000Cell;
            }
        }
        #endregion
        
        #region Fields
        private WinCell mUIItem50000Cell;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIRow0Row1 : WinRow
    {
        
        public UIRow0Row1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinRow.PropertyNames.Value, ";1;1;0;Kreirani Novi;2911933120003;033/534-232;he", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinRowHeader UIItemRowHeader
        {
            get
            {
                if ((this.mUIItemRowHeader == null))
                {
                    this.mUIItemRowHeader = new WinRowHeader(this);
                    #region Search Criteria
                    this.mUIItemRowHeader.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIItemRowHeader;
            }
        }
        #endregion
        
        #region Fields
        private WinRowHeader mUIItemRowHeader;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UILicnipodaciWindow : WinWindow
    {
        
        public UILicnipodaciWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "groupBox2";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinGroup UILicnipodaciGroup
        {
            get
            {
                if ((this.mUILicnipodaciGroup == null))
                {
                    this.mUILicnipodaciGroup = new WinGroup(this);
                    #region Search Criteria
                    this.mUILicnipodaciGroup.SearchProperties[WinControl.PropertyNames.Name] = "Licni podaci";
                    this.mUILicnipodaciGroup.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUILicnipodaciGroup;
            }
        }
        #endregion
        
        #region Fields
        private WinGroup mUILicnipodaciGroup;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIForm1TitleBar : WinTitleBar
    {
        
        public UIForm1TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UICloseButton
        {
            get
            {
                if ((this.mUICloseButton == null))
                {
                    this.mUICloseButton = new WinButton(this);
                    #region Search Criteria
                    this.mUICloseButton.SearchProperties[WinButton.PropertyNames.Name] = "Close";
                    this.mUICloseButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUICloseButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUICloseButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIIzracunajcijenuisporWindow : WinWindow
    {
        
        public UIIzracunajcijenuisporWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "button1";
            this.WindowTitles.Add("Form1");
            #endregion
        }
        
        #region Properties
        public WinButton UIIzracunajcijenuisporButton
        {
            get
            {
                if ((this.mUIIzracunajcijenuisporButton == null))
                {
                    this.mUIIzracunajcijenuisporButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIIzracunajcijenuisporButton.SearchProperties[WinButton.PropertyNames.Name] = "Izracunaj cijenu isporuke";
                    this.mUIIzracunajcijenuisporButton.WindowTitles.Add("Form1");
                    #endregion
                }
                return this.mUIIzracunajcijenuisporButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIIzracunajcijenuisporButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIZadaca3Window : WinWindow
    {
        
        public UIZadaca3Window()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Zadaca 3";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "CabinetWClass";
            this.WindowTitles.Add("Zadaca 3");
            #endregion
        }
        
        #region Properties
        public UIZadaca3TitleBar UIZadaca3TitleBar
        {
            get
            {
                if ((this.mUIZadaca3TitleBar == null))
                {
                    this.mUIZadaca3TitleBar = new UIZadaca3TitleBar(this);
                }
                return this.mUIZadaca3TitleBar;
            }
        }
        #endregion
        
        #region Fields
        private UIZadaca3TitleBar mUIZadaca3TitleBar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "15.0.26208.0")]
    public class UIZadaca3TitleBar : WinTitleBar
    {
        
        public UIZadaca3TitleBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Zadaca 3");
            #endregion
        }
        
        #region Properties
        public WinButton UIMinimizeButton
        {
            get
            {
                if ((this.mUIMinimizeButton == null))
                {
                    this.mUIMinimizeButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIMinimizeButton.SearchProperties[WinButton.PropertyNames.Name] = "Minimize";
                    this.mUIMinimizeButton.WindowTitles.Add("Zadaca 3");
                    #endregion
                }
                return this.mUIMinimizeButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIMinimizeButton;
        #endregion
    }
}
