library(factoextra)
library(ISLR)
library(cluster)
library(NbClust)
library(fpc)
library(dbscan)
library(BBmisc)
library(ClusterR)
#1)
data("USArrests")
USA = normalize(USArrests,range=c(0,1))
#a)
data.sl = eclust(USA,FUNcluster =c("agnes"),hc_metric ="euclidean",hc_method="single")
#b)
data.cl = eclust(USA,FUNcluster =c("agnes"),hc_metric ="euclidean",hc_method="complete")
#c)
data.al = eclust(USA,FUNcluster =c("agnes"),hc_metric ="euclidean",hc_method="average")
#d)
data.wd = eclust(USA,FUNcluster =c("agnes"),hc_metric ="euclidean",hc_method="ward.D2")

plot(data.sl)
plot(data.cl)
plot(data.al)
plot(data.wd)


#a)
data.sl2 = eclust(USA,FUNcluster =c("agnes"),hc_metric ="pearson",hc_method="single")
#b)
data.cl2 = eclust(USA,FUNcluster =c("agnes"),hc_metric ="pearson",hc_method="complete")
#c)
data.al2 = eclust(USA,FUNcluster =c("agnes"),hc_metric ="pearson",hc_method="average")
#d)
data.wd2 = eclust(USA,FUNcluster =c("agnes"),hc_metric ="pearson",hc_method="ward.D2")


plot(data.sl2)
plot(data.cl2)
plot(data.al2)
plot(data.wd2)

a=silhouette(data.sl$cluster,dist(USA))
fviz_silhouette(a)
b=silhouette(data.cl$cluster,dist(USA))
fviz_silhouette(b)
c=silhouette(data.al$cluster,dist(USA))
fviz_silhouette(c)
d=silhouette(data.wd$cluster,dist(USA))
fviz_silhouette(d)
e=silhouette(data.sl2$cluster,dist(USA))
fviz_silhouette(e)
f=silhouette(data.cl2$cluster,dist(USA))
fviz_silhouette(f)
g=silhouette(data.al2$cluster,dist(USA))
fviz_silhouette(g)
h=silhouette(data.wd2$cluster,dist(USA))
fviz_silhouette(h)


#2)

data(iris)
Iris = iris[,-5]
Iris = normalize(Iris,range=c(0,1))
NbClust(Iris,method="centroid")
NbClust(Iris,method="ward.D2")
dbscan::kNNdistplot(Iris,k = 2)
Iris.db = fpc::dbscan(Iris,MinPts = 4,eps = 0.5)
Iris.wd = eclust(Iris,FUNcluster =c("agnes"),hc_metric ="euclidean",hc_method="ward.D2")
Iris.km = eclust(Iris,FUNcluster =c("kmeans"),hc_metric ="euclidean")
Iris.pm = eclust(Iris,FUNcluster = c("pam"),hc_metric = "euclidean")
fviz_silhouette(silhouette(Iris.db$cluster,dist(Iris)))
fviz_silhouette(silhouette(Iris.wd$cluster,dist(Iris)))
fviz_silhouette(silhouette(Iris.km$cluster,dist(Iris)))
fviz_silhouette(silhouette(Iris.pm$cluster,dist(Iris)))
iris$Species = ifelse(iris$Species == "setosa",as.numeric(0),ifelse(iris$Species=="versicolor",1,2))
iris$Species = as.numeric(iris$Species)
Iris.wd$height = round(Iris.wd$height,6)
Iris.wd["height"<0] = 0
Iris.wd$height
c = cutree(Iris.wd,h=0.5)
iris = transform(iris,Species = as.numeric(Species))
res = external_validation(iris$Species,Iris.km$cluster,method="adjusted_rand_index",summary_stats = TRUE)
res = external_validation(iris$Species,Iris.pm$cluster,method="adjusted_rand_index",summary_stats = TRUE)
res = external_validation(iris$Species,Iris.db$cluster,method="adjusted_rand_index",summary_stats = TRUE)
res = external_validation(iris$Species,cutree(Iris.wd,k =4,h = 0.5),method="adjusted_rand_index",summary_stats = TRUE)
res

#3)
data(College)
College$is_elite = as.factor(ifelse(College$Top10perc>=50,"Elite","Not Elite"))
College$Private = as.factor(College$Private)
College$accept_rate = College$Accept/College$Apps
set.seed(123)
gower_dist = daisy(College,metric="gower")
col.comp = hclust(gower_dist,method="complete")
col.wd = hclust(gower_dist,method="ward.D2")
plot(col.comp,labels = FALSE)
plot(col.wd,labels = FALSE)